export function App() {
  return (
    <main
      style={{
        minHeight: '100vh',
        display: 'grid',
        placeItems: 'center',
        backgroundColor: '#ffffff',
        color: '#000000',
        margin: 0
      }}
    >
      <h1 style={{ margin: 0, fontSize: '2rem', fontWeight: 500 }}>Generated by AI</h1>
    </main>
  )
}
